### ISSUE TITLE
Printing floats is broken

### ISSUE THREAD

**Issue by Eiyeron** [Eiyeron/squirrel#1]
``` lua
>print(2.5)
1.061e-314

>print(2.5.tostring())
1.061e-314

>print(2)
2

>print(2.5+2.5).tointeger())
5

>print(2.5+2.5)
1.06929e-314
```

**Comment by Eiyeron** [comment]
Looks like it comes from sqvm.cpp:289, needs more testing.

``` c++
scsprintf(_sp(sq_rsl(NUMBER_MAX_CHAR+1)),sq_rsl(NUMBER_MAX_CHAR),_SC("%g"),_float(o));
```

**Comment by Vogtinator** [comment]
Edit: Forget that, the C spec forces floats to be passed as double.
You might still try to compile it with doubles instead of floats.

**Comment by Eiyeron** [comment]
Compiling with using doubles instead of floats yields the same result.

Also, another point where the conversion fails is at format function (`sqstd_format`), which also calls  scsprintf (which is a direct wrapper of snprintf).

``` lua
print(format("%f %g", 2.5, 2.5))
0.000000 1.41998e-315
```

I may need to contact you, Vog, to determine how to work with a debugger on firebird.

Edit : looks like the the format function somehow fails to correctly get the float value, for instance in `sqstd_format:142`, `tf` is equals 0.

Edit 2 : is there known issues with non strict aliasing float values? If I remove `-fno-strict-aliasing`, I get such warnings : 

``` make
sqvm.cpp: In member function ‘bool SQVM::Execute(SQObjectPtr&, SQInteger, SQInteger, SQObjectPtr&, SQBool, SQVM::ExecutionType)’:
sqvm.cpp:722:66: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
             case _OP_LOADFLOAT: TARGET = *((const SQFloat *)&arg1); continue;
                                                                  ^
sqvm.cpp:919:65: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
                     val._unVal.fFloat = *((const SQFloat *)&arg1);
```

**Comment by Vogtinator** [comment]
I noticed a few things:

`As nspireio doesn't take over printf`:

link with "--nspireio" and it will transparently wrap all reads and writes to stdin, stdout and stderr.
In that case you must not do nspireio initialization yourself, but you can use the default nio_console.

`# Ndless doesn't provide a ndless-ar wrapper`

Use `arm-none-eabi-ar`.

Also, I just built it and it works fine here.
![sqworks](https://cloud.githubusercontent.com/assets/1622084/15288366/88c38a16-1b6a-11e6-847f-40060fe1f1c2.png)

I just pushed https://github.com/ndless-nspire/Ndless/commit/dfedee01a837c06a87aafea4f8baa119deae3bee from my fork upstream, maybe that workaround broke it?

**Comment by Eiyeron** [comment]
Welp, Just updating ndless_ressources didn't fixed anything at all.

> Use arm-none-eabi-ar.

Thanks for pointing me that I frogot to correct the archiver on the stdlib's side.

> link with "--nspireio" and it will transparently wrap all reads and writes to stdin, stdout and stderr.
> In that case you must not do nspireio initialization yourself, but you can use the default nio_console.

Does it impact the final resilt and the result of print?

So yeah, i totally have no clue why I have such results with floats. 8|

**Comment by Vogtinator** [comment]
> Does it impact the final resilt and the result of print?

It shouldn't make a difference.

> So yeah, i totally have no clue why I have such results with floats. 8|

Have you tried what I wrote in the comment?

**Comment by Eiyeron** [comment]
~~Couldn't find where to use nspireio's flag (looks like genzehn should be the one to use the flag but the last version doesn't support it)~~, but the other things like trying using doubles or int64.

Nevermind, I'm an idiot and found how to pass arguments to the linker, but the result doesn't change a bit.

Edit 2 : New branch, nS_floating_hell. Now, I'm just turning crazy. It breaks everywhere since I tried to use --nspireio

**Comment by Vogtinator** [comment]
The --nspireio flag should've made it easier to port, as no nspire-specific code would've been needed for IO.

Have you checked out https://github.com/ndless-nspire/Ndless/commit/dfedee01a837c06a87aafea4f8baa119deae3bee yet?

**Comment by Eiyeron** [comment]
I did yeah. Nothing changed. Next time I'm busting going to write lists of what's done.
Well now there is almost any endless code anymore. Just tweaks here and there (and N2DLib integration).

**Comment by Vogtinator** [comment]
I wonder what the difference between my toolchain/SDK build and yours is.
I mean, we compiled the same source with the same flags and get a different result? WTH.

**Comment by Eiyeron** [comment]
I'm using the lastest revision of ndless, by the way. Recompiled everything and pushed 6f31dcd to clean every reference to nspireio's library.

My toolchain (if it can help) : 
- binutils-2.26/
- gcc-6.1.0/
- gdb-7.11/
- newlib-2.4.0/

**Comment by Vogtinator** [comment]
Do the SDK samples (especially newlib) work?

**Comment by Eiyeron** [comment]
@Vogtinator Tried with the ndless_ressources of the 3.1 bundle, and it works. So there is an issue with this.

**Comment by Vogtinator** [comment]
Can you clarify what you tested exactly?

**Comment by Eiyeron** [comment]
Tried with the last revision of ndless_resource(commit dfedee01a837c06a87aafea4f8baa119deae3bee, manually built) (after building it, pushing it to my calc and trying executing squirrel). This version doesn't have the floating point working.

Then I tried with the version bundled here : https://tiplanet.org/forum/archives_voir.php?id=3891
Pushing it to  my calc, rebooting, trying squirrel. Saw that `print(2.5)` actually prints 2.5.

**Comment by Vogtinator** [comment]
Can you set a breakpoint on _start and print `sp`?

**Comment by Eiyeron** [comment]
How? I don't have a clue on how to make gdb work, if you mean this.

**Comment by Vogtinator** [comment]
No gdb required, you can also edit ndless-sdk/system/crt0.S, add a `bkpt` after `_start` and invoke `r` in firebird's debugger.

**Comment by Eiyeron** [comment]
That's another problem. I can't use firebird anymore. It automatically crashes when launching the emulation.

Explanation :  I tried updating firebird from an unknown version to the current one, but now, the emulator instantly crashed with this thing : `firebird: ../core/translate_x86_64.c:53: emit_call_nosave: Assertion`false' failed.`

**Comment by Vogtinator** [comment]
Even the released version? Is it possible that your compiler changed to gcc 6, which I haven't tried firebird yet?

I have an idea what's going on. Your build of squirrel causes `sp` to be unaligned and the original 3.1 ndless resources has the same bug, canceling each other out.

**Comment by Eiyeron** [comment]
Yup, (finally) 6.1.1. So what now?

**Comment by Vogtinator** [comment]
You could help me debugging firebird (I haven't upgraded to gcc6 yet) or use the old nspire_emu meanwhile.

**Comment by Eiyeron** [comment]
Mmhm, sounds a good idea. How do I help you debugging it? I have almost no debugging expericence with gdb only, only with an IDE or DDD.

**Comment by Vogtinator** [comment]
Any IDE is fine, as long as it can set breakpoints and show values of variables.

**Comment by Eiyeron** [comment]
Backtrace when crashing

```
clone() from libc.so.6
start_thread() from libpthread.so.0
?? () from libQt5Core.so.5
EmuThread::run()
emu_loop()
translate()
emit_call_nosave()
emit_call_nosave.part.4.lto_priv()
__assert_fail() from libc.so.6
__assert_fail_base() from libc.so.6
abort() from libc.so.6
raise() from libc.so.6
```

**Comment by Vogtinator** [comment]
I'll need some more than that, because that is the only possible path for this bug anyway.
Could you provide the locals or at least line numbers?

Meanwhile I built firebird with GCC 6 and except some wrong warnings, everything works fine here.

**Comment by Eiyeron** [comment]
Well, I can't find a way to open the source files with a local build, even though there is the -g flag in compilation.

**Comment by Vogtinator** [comment]
You're apparently building in release mode. For debugging. run qmake with`qmake-qt5 "CONFIG+=debug" firebird.pro`. I fear that it works with that configuration...

**Comment by Eiyeron** [comment]
```
...
EmuThread::run => emuthread.cpp:168
emu_loop => emu.cpp:334
cpu_arm_loop => cpu.cpp:88
translate => translate_x86_64.c:850
emit_call_nosave => translate_x86_64.c:53
...
```

**Comment by Vogtinator** [comment]
I see the issue, the firebird binary is too far from the JIT code.
Can you provide the output of `/proc/$(pidof firebird)/maps` when it crashed (paste somewhere else, it's rather long)?

**Comment by Eiyeron** [comment]
http://hastebin.com/fuvapeyocu.avrasm

Huh, it's the log of another execution, is it bad?

**Comment by Vogtinator** [comment]
Simple cause: The binary is not loaded into the 32-bit space, which it has to be for the JIT.
This may be because of ASLR enabled (disable temporarily by doing `echo 0 | sudo tee /proc/sys/kernel/randomize_va_space`). You can also forcibly disable PIC/PIE in the compile flags.

I have to find a way to force firebird to get loaded into a certain range, but that may not be possible.

**Comment by Eiyeron** [comment]
That's by disabling the -fPIC flag, right? If yes, it makes the compilation unable to finish because it needs relocatable code.

**Comment by Vogtinator** [comment]
It shouldn't. Maybe it's still enabled during link time?

**Comment by Eiyeron** [comment]
```
/usr/include/qt/QtCore/qglobal.h:1090:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
 #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "
```

Looks like I'm screwed.

**Comment by Vogtinator** [comment]
Have you tried disabling ASLR yet?

**Comment by Eiyeron** [comment]
I got that it's adress space layout randomisation (thanks 3DS's OS 11.0 for this) but I don't know how to disable it.

**Comment by Vogtinator** [comment]
I wrote how in my comment.

**Comment by Eiyeron** [comment]
Sorry. Doesn't work either.

**Comment by Vogtinator** [comment]
One last try, which is a real hack: Replace line 35 in asmcode_x86_64.S with: `movabs $arm, %rbx`

**Comment by Eiyeron** [comment]
Same assertion.

``` asm
translation_enter: .global translation_enter
    push    %rbp
    mov     %rsp, %rbp
    push    %rbx
    push    %rsi
    push    %rdi
    mov     %rsp, in_translation_rsp(%rip)

    movabs  $arm, %rbx
    mov     ARM_PC(%rbx), %eax
    jmp     translation_next
```

Hope I didn't mess up.

**Comment by Vogtinator** [comment]
Hm, that's an illegal optimization, I'd say it's a bug in the toolchain then.

Run `objdump -d asmcode_x86_64.o` and paste the translation_enter section.

**Comment by Eiyeron** [comment]
http://hastebin.com/vonesehavo.xml

**Comment by Vogtinator** [comment]
Looks fine. Could you paste the translation_enter section of the final firebird executable?

**Comment by Eiyeron** [comment]
(PS : I kept your hack)

```
00000000000169ee <translation_enter>:
   169ee:   55                      push   %rbp
   169ef:   48 89 e5                mov    %rsp,%rbp
   169f2:   53                      push   %rbx
   169f3:   56                      push   %rsi
   169f4:   57                      push   %rdi
   169f5:   48 89 25 24 ee f3 00    mov    %rsp,0xf3ee24(%rip)        # f55820 <in_translation_rsp>
   169fc:   48 bb 00 1e 6f 00 00    movabs $0x6f1e00,%rbx
   16a03:   00 00 00 
   16a06:   8b 43 3c                mov    0x3c(%rbx),%eax
   16a09:   eb 08                   jmp    16a13 <translation_next>
```

**Comment by Vogtinator** [comment]
Looks like it uses a relocation. What about:

`mov      $arm, %rbx`

so, without `abs`?

**Comment by Eiyeron** [comment]
```
g++  -o firebird os-linux.o translate_x86_64.o asmcode.o asmcode_x86_64.o lcdwidget.o mainwindow.o main.o flashdialog.o emuthread.o qmlbridge.o qtkeypadbridge.o arm_interpreter.o coproc.o cpu.o thumb_interpreter.o usblink_queue.o armsnippets_loader.o casplus.o des.o disasm.o gdbstub.o gif.o interrupt.o keypad.o lcd.o link.o mem.o misc.o mmu.o schedule.o serial.o sha256.o usb.o usblink.o qtframebuffer.o debug.o flash.o emu.o usblinktreewidget.o qrc_resources.o moc_emuthread.o moc_lcdwidget.o moc_flashdialog.o moc_mainwindow.o moc_qmlbridge.o moc_usblinktreewidget.o   -lz -lQt5QuickWidgets -lQt5Widgets -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
/usr/bin/ld: asmcode_x86_64.o: relocation R_X86_64_32S against `arm' can not be used when making a shared object; recompile with -fPIC
asmcode_x86_64.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:368: recipe for target 'firebird' failed
make: *** [firebird] Error 1
```

I'll try to force -fPIC for  asmcode_x86_64 and I'll give you the result.
Edit : nope, it's already given the flag.

**Comment by Vogtinator** [comment]
I'll try to reproduce the issue here and try to find a solution as well.
For now, you need to find a way to either turn ASLR off, force the binary to be in a specified location in memory or generate a non-relocatable executable.

Just to verify, what's the output of:

```
file firebird
readelf -h firebird
```

**Comment by Eiyeron** [comment]
```
$file firebird
firebird: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=0d13bcac42283066d59d6137aa65da96991b0075, not stripped

$readelf -h firebird
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 03 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - GNU
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x132c0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          6061312 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         9
  Size of section headers:           64 (bytes)
  Number of section headers:         40
  Section header string table index: 37
```

**Comment by Vogtinator** [comment]
Ok, I can reproduce by adding the "-pie" linker flag. Try to remove it.

**Comment by Eiyeron** [comment]
I don't have it.

**Comment by Vogtinator** [comment]
Next attempt: https://wiki.archlinux.org/index.php/Dolphin_emulator#Launching_games_fails_with_.22WriteRest_Op.22_error

So, add `-fno-pie` to the CXX and CFLAGS

**Comment by Eiyeron** [comment]
It worked. So, back to squirrel debugging?

**Comment by Vogtinator** [comment]
Yay! Now you can get back to the real bugs :P
Can you make a PR to firebird?

**Comment by Eiyeron** [comment]
Sure, I can, lemme find where to put it.

Edit : okay, our issues comes from hardening-wrapper, which is installed on Archlinux which wraps gcc and force adds some flags if you don't manually remove them.

**Comment by Vogtinator** [comment]
> Edit : okay, our issues comes from hardening-wrapper, which is installed on Archlinux which wraps gcc and force adds some flags if you don't manually remove them.

I expected something like this. It's the case for debian as well, if configured to. There has to be a better way to get the JIT working with ASLR enabled as well.

**Comment by Eiyeron** [comment]
Mmh, should this issue belong to Ndless or Squirrel now? I'm trying to search where it could fail but I have to find anything to fix this issue.

**Comment by Vogtinator** [comment]
As squirrel is pure C code, wrong stack alignment can only be caused by the SDK, toolchain or some setup issues.
Have you tried the Ndless samples yet? If they work, it's most likely the setup, if they don't, it's a bug in the Ndless SDK.

**Comment by Eiyeron** [comment]
They do work, actually, this is probably the only project I used or programmed that had this particular - hold on, I edited helloworld-cpp to add a float to a printf and it didn't worked the same way than nSquirrel.

``` cpp
printf("lo\n %f", 2.5); // Prints 0.0000...
```

So yeah, maybe there is an issue with 3.1. As it doesn't impact squirrel only, I think I'm going to close this issue.

Edit : I compiled with dfedee01a837c06a87aafea4f8baa119deae3bee version of Ndless and put the zehn version to my OS3.1 emulator. It should do the same with my 3.1 Nspire

**Comment by Vogtinator** [comment]
> So yeah, maybe there is an issue with 3.1

Of course, 3.1 is known to be broken.

**Comment by Eiyeron** [comment]
Ah? I've been told to keep this version because it's the version with the fastest transfer rate. So, should updating be required?

**Comment by Vogtinator** [comment]
I recommend that anyway, because free() on 3.1 is broken in a weird way as well, see https://github.com/ndless-nspire/Ndless/issues/19

**Comment by Eiyeron** [comment]
Oh really? That'd explain some of the random reboots I had before that. Welp, looks like the case is closed. At least we nailed an issue with firebird! :p

**Comment by Eiyeron** [comment]
Welp:

> This is known and a bug in OS 3.1 (or syscall handler, not sure).
> Ndless 3.9 is already compatible with OS 3.6 and 3.1 as long as you use the appropriate installers.
> 
> Install the old ndless 3.1 and then swap ndless_resources.tns and reboot. If that doesn't work, please open another issue here, that'd be a bug.

That's exactly what I did though. But yeah, updating.
Edit : wait, not reboot-proof? Really? :/
